services:
  - type: web
    name: valen-dev-helpers
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: API_KEY
        sync: false